/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aris J
 */
public class futama extends javax.swing.JFrame {

    /**
     * Creates new form futama
     */
    public futama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LABEL1 = new javax.swing.JLabel();
        BUTONTON = new javax.swing.JButton();
        LABEL2 = new javax.swing.JLabel();
        LABEL3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LABEL1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LABEL1.setText("NAMA");
        LABEL1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BUTONTON.setText("KLIK DISINI");
        BUTONTON.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BUTONTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUTONTONActionPerformed(evt);
            }
        });

        LABEL2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LABEL2.setText("NIM");
        LABEL2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        LABEL3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LABEL3.setText("KELAS");
        LABEL3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LABEL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABEL2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABEL3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BUTONTON, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addGap(0, 145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(LABEL1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABEL2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABEL3)
                .addGap(26, 26, 26)
                .addComponent(BUTONTON)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BUTONTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUTONTONActionPerformed
        // TODO add your handling code here:
        LABEL1.setText("Nama Saya Julian Arisky Lase");
        LABEL2.setText("NIM Saya 10118385");
        LABEL3.setText("Saya Mahasiswa IF-9");
    }//GEN-LAST:event_BUTONTONActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUTONTON;
    private javax.swing.JLabel LABEL1;
    private javax.swing.JLabel LABEL2;
    private javax.swing.JLabel LABEL3;
    // End of variables declaration//GEN-END:variables
}
